-- select *
-- from employees
-- where salary >12000;


-- select *
-- from employees
-- where employee_id = '175';


-- select last_name,salary
-- from employees
-- where salary between 5000 and 12000;

-- select last_name,salary
-- from employees
-- where last_name IN ('Mavris', 'Baer');

-- select last_name,salary
-- from employees
-- where salary not between 5000 and 12000;


-- select last_name,salary,department_id
-- from employees  
-- where salary between 5000 and 12000
-- and department_id IN ('20', '70') ;


-- select last_name,salary,department_id,hire_date
-- from employees
-- where hire_date between '01/01/06' and '31/12/06';

-- select first_name,salary,department_id
-- from employees  
-- where first_name like '__a%';

-- select first_name,salary,department_id
-- from employees  
-- where last_name like '%a%' and last_name like '%i%';
